# Generated by Django 2.2.28 on 2023-01-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Напишите свой комментарий, но учтите, что вы не сможете изменить его.', verbose_name='Текст комментария'),
        ),
    ]
